version: "2"

services:
  jira:
    image: cptactionhank/atlassian-jira-software
    environment:
      VIRTUAL_HOST: jira.${REVERSE_PROXY_DOMAIN}
      VIRTUAL_PORT: 8080
      X_PROXY_NAME: jira.${REVERSE_PROXY_DOMAIN}
      X_PROXY_PORT: ${REVERSE_PROXY_PORT}
      X_PROXY_SCHEME: ${REVERSE_PROXY_PROTO}
    links:
      - db
      - ldap
    volumes:
      - jira-data:/var/atlassian/jira
    networks:
      - default
      - reverse-proxy-network

  confluence:
    image: cptactionhank/atlassian-confluence
    environment:
      VIRTUAL_HOST: confluence.${REVERSE_PROXY_DOMAIN}
      VIRTUAL_PORT: 8090
      X_PROXY_NAME: confluence.${REVERSE_PROXY_DOMAIN}
      X_PROXY_PORT: ${REVERSE_PROXY_PORT}
      X_PROXY_SCHEME: ${REVERSE_PROXY_PROTO}
    links:
      - db
      - ldap
    volumes:
      - confluence-data:/var/atlassian/confluence
    networks:
      - default
      - reverse-proxy-network

  gitbucket:
    image: f99aq8ove/gitbucket
    environment:
      VIRTUAL_HOST: git.${REVERSE_PROXY_DOMAIN}
      VIRTUAL_PORT: 8080
      GITBUCKET_DB_URL: jdbc:postgresql://db/gitbucket
      GITBUCKET_DB_USER: gitbucket
      GITBUCKET_DB_PASSWORD: gitbucket
    links:
      - db
      - ldap
    volumes:
      - gitbucket-data:/gitbucket
    networks:
      - default
      - reverse-proxy-network

  jenkins:
    image: jenkins
    environment:
      VIRTUAL_HOST: jenkins.${REVERSE_PROXY_DOMAIN}
      VIRTUAL_PORT: 8080
    links:
      - ldap
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - default
      - reverse-proxy-network

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss
    environment:
      VIRTUAL_HOST: artifactory.${REVERSE_PROXY_DOMAIN}
      VIRTUAL_PORT: 8081
    links:
      - ldap
      - db
    volumes:
      - artifactory-data:/var/opt/jfrog/artifactory/data
      - artifactory-conf:/var/opt/jfrog/artifactory/etc
    networks:
      - default
      - reverse-proxy-network

  sonarqube:
    image: sonarqube
    links:
      - db
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube-conf:/opt/sonarqube/conf
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-plugins:/opt/sonarqube/lib/bundled-plugins

  mattermost:
    image: mattermost/mattermost-prod-app
    environment:
      VIRTUAL_HOST: mattermost.${REVERSE_PROXY_DOMAIN}
      VIRTUAL_PORT: 8080
      MATTERMOST_ENABLE_SSL: ${REVERSE_PROXY_HTTPS}
      DB_HOST: db
      MM_DBNAME: mattermost
      MM_USERNAME: mattermost
      MM_PASSWORD: mattermost
    links:
      - db
    volumes:
      - mattermost-data:/mattermost/data
      - mattermost-config:/mattermost/config
    networks:
      - default
      - reverse-proxy-network

  owncloud:
    image: owncloud
    environment:
      VIRTUAL_HOST: cloud.${REVERSE_PROXY_DOMAIN}
      VIRTUAL_PORT: 80
    links:
      - ldap
      - db
    volumes:
      - owncloud-data:/var/www/html/data
      - owncloud-config:/var/www/html/config
      - owncloud-apps:/var/www/html/apps
    networks:
      - default
      - reverse-proxy-network

  db:
    build: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  ldap:
    image: osixia/openldap
    environment:
      LDAP_DOMAIN: example.com
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d

volumes:
  jira-data:
    driver: local
  confluence-data:
    driver: local
  gitbucket-data:
    driver: local
  jenkins-data:
    driver: local
  artifactory-data:
    driver: local
  artifactory-conf:
    driver: local
  sonarqube-conf:
    driver: local
  sonarqube-data:
    driver: local
  sonarqube-extensions:
    driver: local
  sonarqube-plugins:
    driver: local
  mattermost-data:
    driver: local
  mattermost-config:
    driver: local
  owncloud-data:
    driver: local
  owncloud-config:
    driver: local
  owncloud-apps:
    driver: local
  db-data:
    driver: local
  ldap-data:
    driver: local
  ldap-config:
    driver: local

networks:
  reverse-proxy-network:
    external:
      name: ${REVERSE_PROXY_NETWORK}
